In [2]:
import json
import pandas as pd
import itertools
from itertools import tee
import numpy as np
import math
import datetime
import time
from geopy.geocoders import Nominatim
from geopy.distance import geodesic

In [3]:
with open('histloc.json', encoding='utf-8') as data_file:
    data = json.loads(data_file.read())

df = pd.DataFrame(data['locations'])

In [ ]:
df = df[df.accuracy < 100] #Ignore locations with accuracy estimates over 1000m
df.reset_index(drop=True, inplace=True)

In [493]:
df_novo_h = df.head(10001)
#df_novo_h['timestampMs'] = df_novo_h['timestampMs'].map(lambda x: int(x)/1000)
#df_novo_h.reset_index(drop=True, inplace=True)
df_novo_h.dtypes

accuracy            float64
activity             object
altitude            float64
heading             float64
latitudeE7            int64
longitudeE7           int64
timestampMs          object
velocity            float64
verticalAccuracy    float64
dtype: object

In [1]:
menorData = min(df_novo_h["timestampMs"])
maiorData = max(df_novo_h["timestampMs"])

print('De:', menorData)
print('Até:', maiorData)
print(maiorData - menorData)

NameError: name 'df_novo_h' is not defined

In [255]:
def pairwise(iterable):
    a, b = tee(iterable)
    next(b, None)
    return zip(a, b)

nan

In [256]:
df_novo_h[df_novo_h['velocity'] > 0.0]

,accuracy,activity,altitude,heading,latitudeE7,longitudeE7,timestampMs,velocity,verticalAccuracy
178,11.0,NaN,34.0,45.0,-129988643,-384627446,1546859152113,2.0,16.0
179,8.0,NaN,32.0,61.0,-129988939,-384627822,1546859151000,1.0,16.0
494,5.0,NaN,-8.0,221.0,-128959193,-383293486,1546809322000,10.0,6.0
495,4.0,NaN,-7.0,221.0,-128946933,-383283162,1546809307000,10.0,6.0
496,5.0,NaN,-9.0,219.0,-128938326,-383275658,1546809292000,8.0,6.0
497,4.0,NaN,-6.0,226.0,-128924780,-383264559,1546809276000,13.0,6.0
498,5.0,NaN,-6.0,227.0,-128909798,-383247486,1546809260000,17.0,6.0
499,4.0,NaN,-7.0,225.0,-128896336,-383232445,1546809245000,11.0,6.0
500,5.0,NaN,-9.0,227.0,-128884824,-383218862,1546809230000,12.0,6.0
501,5.0,NaN,-7.0,226.0,-128862743,-383194364,1546809200000,10.0,6.0
502,4.0,NaN,-2.0,227.0,-128854763,-383185106,1546809184000,6.0,4.0
503,4.0,NaN,3.0,227.0,-128846849,-383176694,1546809168000,7.0,4.0
504,4.0,"[{'timestampMs': '1546809149235', 'activity': ...",2.0,228.0,-128841214,-383169989,1546809153000,5.0,6.0
506,5.0,NaN,6.0,226.0,-128834650,-383162195,1546809123000,4.0,6.0
507,4.0,NaN,8.0,228.0,-128829686,-383157151,1546809107000,4.0,6.0
509,3.0,NaN,8.0,226.0,-128825578,-383152696,1546809076000,1.0,6.0
510,3.0,NaN,10.0,228.0,-128824878,-383152135,1546809061000,2.0,6.0
511,4.0,NaN,11.0,227.0,-128817396,-383143426,1546809045000,10.0,6.0
512,4.0,NaN,8.0,227.0,-128808357,-383133239,1546809030000,7.0,6.0
513,6.0,NaN,11.0,227.0,-128804526,-383129347,1546809014000,5.0,6.0
514,4.0,NaN,8.0,209.0,-128782970,-383107717,1546808969000,9.0,6.0
515,4.0,NaN,17.0,228.0,-128768179,-383094233,1546808954000,16.0,6.0
516,4.0,NaN,18.0,276.0,-128759367,-383082140,1546808938000,4.0,6.0
517,4.0,"[{'timestampMs': '1546808923838', 'activity': ...",17.0,46.0,-128768591,-383089773,1546808922000,13.0,6.0
518,3.0,NaN,13.0,43.0,-128783166,-383105293,1546808907000,17.0,4.0
519,4.0,NaN,11.0,47.0,-128801186,-383124485,1546808891000,16.0,6.0
520,5.0,NaN,18.0,25.0,-128812337,-383134549,1546808875000,6.0,6.0
521,3.0,NaN,10.0,289.0,-128817146,-383127645,1546808860000,9.0,4.0
522,4.0,NaN,9.0,305.0,-128825702,-383116758,1546808844000,9.0,6.0
550,3.0,NaN,11.0,302.0,-128831449,-383109385,1546808408000,1.0,8.0
...,...,...,...,...,...,...,...,...,...
8892,4.0,NaN,14.0,136.0,-129995826,-384603025,1545429795000,9.0,6.0
8893,3.0,NaN,12.0,123.0,-129986414,-384616702,1545429780000,13.0,4.0
8894,4.0,NaN,13.0,340.0,-129983039,-384625602,1545429765000,2.0,6.0
8895,5.0,NaN,14.0,29.0,-129986482,-384623369,1545429749000,2.0,8.0
8896,3.0,NaN,22.0,70.0,-129988047,-384628523,1545429733000,5.0,4.0
8961,11.0,NaN,50.0,0.0,-129917965,-384808239,1545423917060,4.0,2.0
9033,8.0,"[{'timestampMs': '1545413398793', 'activity': ...",4.0,124.0,-130022685,-384589582,1545413395363,1.0,16.0
9212,10.0,NaN,-12.0,45.0,-129918338,-384748033,1545387603000,13.0,6.0
9213,12.0,NaN,-17.0,357.0,-129933526,-384753202,1545387588000,14.0,8.0
9214,11.0,NaN,-5.0,298.0,-129953212,-384744952,1545387572000,14.0,6.0
9215,15.0,NaN,-8.0,281.0,-129958549,-384727068,1545387557000,15.0,8.0
9216,5.0,"[{'timestampMs': '1545387536971', 'activity': ...",-3.0,273.0,-129961525,-384704869,1545387541000,13.0,8.0
9217,7.0,NaN,-3.0,273.0,-129962108,-384688078,1545387526000,10.0,8.0
9339,10.0,NaN,61.0,318.0,-129987527,-384633142,1545334804000,1.0,8.0
9535,14.0,"[{'timestampMs': '1545316276060', 'activity': ...",10.0,133.0,-129651865,-384383982,1545316283000,1.0,8.0
9654,3.0,NaN,1.0,76.0,-130056967,-384558957,1545301813000,11.0,3.0
9655,3.0,NaN,1.0,89.0,-130061054,-384571424,1545301798000,8.0,3.0
9656,3.0,NaN,5.0,167.0,-130060691,-384585119,1545301782000,9.0,6.0
9657,3.0,"[{'timestampMs': '1545301760470', 'activity': ...",0.0,165.0,-130047501,-384588078,1545301767000,10.0,6.0
9658,4.0,NaN,4.0,167.0,-130034466,-384591310,1545301751000,10.0,4.0
9659,3.0,NaN,5.0,171.0,-130023638,-384593875,1545301736000,6.0,4.0
9661,3.0,NaN,5.0,157.0,-130008539,-384597321,1545301705000,10.0,4.0
9662,3.0,NaN,5.0,142.0,-130000567,-384603391,1545301690000,2.0,4.0
9663,3.0,NaN,10.0,131.0,-129994485,-384608995,1545301674000,9.0,3.0
9664,3.0,"[{'timestampMs': '1545301661799', 'activity': ...",6.0,106.0,-129988643,-384620763,1545301659000,9.0,4.0
9665,3.0,NaN,16.0,63.0,-129988992,-384630758,1545301643000,3.0,6.0
9863,7.0,"[{'timestampMs': '1545253358515', 'activity': ...",16.0,342.0,-130020760,-384583716,1545253422284,10.0,16.0
9869,5.0,"[{'timestampMs': '1545252758804', 'activity': ...",7.0,222.0,-129912424,-384382544,1545252758536,3.0,12.0
9874,17.0,NaN,-12.0,5.0,-129851244,-384374889,1545252557070,2.0,35.0
9905,15.0,NaN,10.0,302.0,-129651475,-384381404,1545250958000,1.0,12.0

In [855]:
#df_novo_h['timestampMs'] = df_novo_h['timestampMs'].map(lambda x: float(x)/1000).map(datetime.datetime.fromtimestamp)
#df_novo_h.reset_index(drop=True)
df_novo_h['timestampMs']

0      2019-01-07 11:55:22.764
1      2019-01-07 11:55:01.682
2      2019-01-07 11:54:40.326
3      2019-01-07 11:54:00.205
4      2019-01-07 11:53:16.840
5      2019-01-07 11:52:56.600
6      2019-01-07 11:49:21.174
7      2019-01-07 11:48:41.071
8      2019-01-07 11:48:19.913
9      2019-01-07 11:47:37.127
10     2019-01-07 11:47:16.744
11     2019-01-07 11:46:35.609
12     2019-01-07 11:43:13.737
13     2019-01-07 11:37:52.141
14     2019-01-07 11:32:32.196
15     2019-01-07 11:27:27.123
16     2019-01-07 11:25:22.188
17     2019-01-07 11:23:12.989
18     2019-01-07 11:20:56.763
19     2019-01-07 11:18:50.229
20     2019-01-07 11:16:35.679
21     2019-01-07 11:14:35.622
22     2019-01-07 11:12:35.563
23     2019-01-07 11:10:34.340
24     2019-01-07 11:10:20.000
25     2019-01-07 11:10:04.000
26     2019-01-07 11:09:49.000
27     2019-01-07 11:09:34.000
28     2019-01-07 11:09:18.000
29     2019-01-07 11:09:02.000
                 ...
1570   2019-01-05 10:26:15.957
1571   2019-01-05 10:24:13.849
1572   2019-01-05 10:22:11.999
1573   2019-01-05 10:20:06.321
1574   2019-01-05 10:18:04.175
1575   2019-01-05 10:16:00.854
1576   2019-01-05 10:12:14.886
1577   2019-01-05 10:10:13.407
1578   2019-01-05 10:08:36.460
1579   2019-01-05 10:08:17.092
1580   2019-01-05 10:06:09.865
1581   2019-01-05 10:04:30.715
1582   2019-01-05 10:03:07.393
1583   2019-01-05 10:00:54.060
1584   2019-01-05 10:00:45.687
1585   2019-01-05 10:00:32.367
1586   2019-01-05 10:00:11.920
1587   2019-01-05 09:59:26.006
1588   2019-01-05 09:58:20.198
1589   2019-01-05 09:53:22.939
1590   2019-01-05 09:52:10.885
1591   2019-01-05 09:48:47.518
1592   2019-01-05 09:44:38.327
1593   2019-01-05 09:43:21.587
1594   2019-01-05 09:41:15.073
1595   2019-01-05 09:39:53.000
1596   2019-01-05 09:39:38.000
1597   2019-01-05 09:39:22.000
1598   2019-01-05 09:39:06.000
1599   2019-01-05 09:38:51.000
Name: timestampMs, Length: 1600, dtype: datetime64[ns]

In [691]:
lat = df_novo_h['latitudeE7']/int(1e7)
lon = df_novo_h['longitudeE7']/int(1e7)

df_novo_h.head(10)

,accuracy,activity,altitude,heading,latitudeE7,longitudeE7,timestampMs,velocity,verticalAccuracy
0,17.0,"[{'timestampMs': '1546872922499', 'activity': ...",NaN,NaN,-129988405,-384630618,2019-01-07 11:55:22.764,NaN,NaN
1,17.0,NaN,NaN,NaN,-129988404,-384630616,2019-01-07 11:55:01.682,NaN,NaN
2,17.0,NaN,NaN,NaN,-129988286,-384630556,2019-01-07 11:54:40.326,NaN,NaN
3,17.0,NaN,NaN,NaN,-129988291,-384630537,2019-01-07 11:54:00.205,NaN,NaN
4,17.0,NaN,NaN,NaN,-129988447,-384630570,2019-01-07 11:53:16.840,NaN,NaN
5,22.0,"[{'timestampMs': '1546872742374', 'activity': ...",NaN,NaN,-129988338,-384630307,2019-01-07 11:52:56.600,NaN,NaN
6,17.0,"[{'timestampMs': '1546872560914', 'activity': ...",NaN,NaN,-129988324,-384630575,2019-01-07 11:49:21.174,NaN,NaN
7,17.0,NaN,NaN,NaN,-129988252,-384630652,2019-01-07 11:48:41.071,NaN,NaN
8,17.0,NaN,NaN,NaN,-129988259,-384630629,2019-01-07 11:48:19.913,NaN,NaN
9,17.0,"[{'timestampMs': '1546872457061', 'activity': ...",NaN,NaN,-129988289,-384630541,2019-01-07 11:47:37.127,NaN,NaN

In [708]:
lat = iter(df_novo_h['latitudeE7']/int(1e7))
lon = iter(df_novo_h['longitudeE7']/int(1e7))
lt = zip(lat,lon)
prx = zip(lt,lt)

df_teste = pd.DataFrame(list(prx),columns=['origem','destino']).reset_index(drop=True)
df_teste

                          origem                     destino
0     (-12.9988405, -38.4630618)  (-12.9988404, -38.4630616)
1     (-12.9988286, -38.4630556)  (-12.9988291, -38.4630537)
2      (-12.9988447, -38.463057)  (-12.9988338, -38.4630307)
3     (-12.9988324, -38.4630575)  (-12.9988252, -38.4630652)
4     (-12.9988259, -38.4630629)  (-12.9988289, -38.4630541)
5     (-12.9988352, -38.4630529)  (-12.9988352, -38.4630529)
6      (-12.999028, -38.4631269)   (-12.999028, -38.4631269)
7      (-12.999028, -38.4631269)   (-12.999028, -38.4631269)
8      (-12.999028, -38.4631269)   (-12.999028, -38.4631269)
9      (-12.999028, -38.4631269)   (-12.999028, -38.4631269)
10     (-12.999028, -38.4631269)   (-12.999028, -38.4631269)
11     (-12.999028, -38.4631269)   (-12.999029, -38.4631254)
12    (-12.9990361, -38.4631143)  (-12.9990357, -38.4631174)
13    (-12.9990369, -38.4631153)  (-12.9990385, -38.4631141)
14    (-12.9990401, -38.4631113)  (-12.9990408, -38.4631107)
15    (-12.9990416, -38.4631098)  (-12.9990461, -38.4630997)
16    (-12.9990465, -38.4630989)  (-12.9990468, -38.4630982)
17    (-12.9990478, -38.4630961)  (-12.9990486, -38.4630939)
18    (-12.9990586, -38.4630606)  (-12.9990656, -38.4630266)
19    (-12.9990768, -38.4629852)  (-12.9990629, -38.4629678)
20     (-12.9990794, -38.462912)  (-12.9990836, -38.4629002)
21    (-12.9990873, -38.4628911)  (-12.9991007, -38.4628602)
22    (-12.9991044, -38.4628532)  (-12.9991053, -38.4628494)
23    (-12.9991055, -38.4628476)   (-12.999105, -38.4628477)
24    (-12.9991052, -38.4628365)   (-12.9990995, -38.462841)
25     (-12.9990861, -38.462852)   (-12.999065, -38.4628559)
26    (-12.9990721, -38.4628532)  (-12.9988253, -38.4630536)
27    (-12.9992153, -38.4629109)  (-12.9992153, -38.4629109)
28    (-12.9992153, -38.4629109)  (-12.9992153, -38.4629109)
29    (-12.9992153, -38.4629109)  (-12.9992153, -38.4629109)
...                          ...                         ...
4970  (-12.9653339, -38.4383023)  (-12.9653339, -38.4383023)
4971  (-12.9653295, -38.4382813)  (-12.9653405, -38.4383355)
4972  (-12.9653423, -38.4383225)   (-12.9653402, -38.438333)
4973  (-12.9653404, -38.4383331)  (-12.9653428, -38.4383231)
4974  (-12.9653423, -38.4383227)  (-12.9653358, -38.4383223)
4975  (-12.9653425, -38.4383228)  (-12.9653419, -38.4383278)
4976  (-12.9653419, -38.4383278)  (-12.9653419, -38.4383278)
4977  (-12.9653419, -38.4383278)  (-12.9653419, -38.4383278)
4978  (-12.9653419, -38.4383278)  (-12.9653419, -38.4383278)
4979  (-12.9653419, -38.4383278)  (-12.9653419, -38.4383278)
4980  (-12.9653419, -38.4383278)  (-12.9653419, -38.4383278)
4981  (-12.9653423, -38.4383226)  (-12.9653379, -38.4383317)
4982  (-12.9653349, -38.4383074)   (-12.965342, -38.4383219)
4983   (-12.965342, -38.4383223)   (-12.965342, -38.4383219)
4984   (-12.9653255, -38.438303)  (-12.9653349, -38.4383074)
4985  (-12.9653304, -38.4383147)  (-12.9653357, -38.4383219)
4986  (-12.9653404, -38.4383328)  (-12.9653404, -38.4383328)
4987  (-12.9653408, -38.4383334)  (-12.9653408, -38.4383334)
4988  (-12.9653408, -38.4383336)  (-12.9653406, -38.4383331)
4989  (-12.9653408, -38.4383332)  (-12.9653405, -38.4383332)
4990   (-12.965341, -38.4383339)    (-12.965343, -38.438323)
4991  (-12.9653349, -38.4383073)  (-12.9653377, -38.4383287)
4992   (-12.9653379, -38.438329)  (-12.9653482, -38.4383111)
4993  (-12.9653411, -38.4383358)  (-12.9653485, -38.4383467)
4994   (-12.9653422, -38.438322)  (-12.9653303, -38.4383147)
4995   (-12.965321, -38.4383121)  (-12.9653262, -38.4382997)
4996   (-12.9653349, -38.438307)  (-12.9653421, -38.4383222)
4997  (-12.9653414, -38.4383338)  (-12.9653414, -38.4383337)
4998  (-12.9653431, -38.4383229)  (-12.9653433, -38.4383476)
4999  (-12.9653523, -38.4383347)  (-12.9653474, -38.4383233)

[5000 rows x 2 columns]

In [700]:
df_novo_h.head(10)

,accuracy,activity,altitude,heading,latitudeE7,longitudeE7,timestampMs,velocity,verticalAccuracy
0,17.0,"[{'timestampMs': '1546872922499', 'activity': ...",NaN,NaN,-129988405,-384630618,2019-01-07 11:55:22.764,NaN,NaN
1,17.0,NaN,NaN,NaN,-129988404,-384630616,2019-01-07 11:55:01.682,NaN,NaN
2,17.0,NaN,NaN,NaN,-129988286,-384630556,2019-01-07 11:54:40.326,NaN,NaN
3,17.0,NaN,NaN,NaN,-129988291,-384630537,2019-01-07 11:54:00.205,NaN,NaN
4,17.0,NaN,NaN,NaN,-129988447,-384630570,2019-01-07 11:53:16.840,NaN,NaN
5,22.0,"[{'timestampMs': '1546872742374', 'activity': ...",NaN,NaN,-129988338,-384630307,2019-01-07 11:52:56.600,NaN,NaN
6,17.0,"[{'timestampMs': '1546872560914', 'activity': ...",NaN,NaN,-129988324,-384630575,2019-01-07 11:49:21.174,NaN,NaN
7,17.0,NaN,NaN,NaN,-129988252,-384630652,2019-01-07 11:48:41.071,NaN,NaN
8,17.0,NaN,NaN,NaN,-129988259,-384630629,2019-01-07 11:48:19.913,NaN,NaN
9,17.0,"[{'timestampMs': '1546872457061', 'activity': ...",NaN,NaN,-129988289,-384630541,2019-01-07 11:47:37.127,NaN,NaN

In [828]:
t = iter(df_novo_h['timestampMs'])

tmp = zip(t,t)

df_temporario = pd.DataFrame(list(tmp),columns=['chegada','saida']).reset_index(drop=True)

df_teste['saida'] = df_temporario['saida']
df_teste['chegada'] = df_temporario['chegada']

df_teste.head(1)

,origem,destino,chegda,saida,duracao,distancia,chegada
0,"(-12.9988405, -38.4630618)","(-12.9988404, -38.4630616)",2019-01-07 11:55:22.764,2019-01-07 11:55:01.682,00:00:21.082000,2.4354733769634586e-05 km,2019-01-07 11:55:22.764

In [859]:
origem = iter(df_teste['origem'])
destino = iter(df_teste['destino'])
chegada = iter(df_teste['chegda'])
saida = iter(df_teste['saida'])

caminho = zip(origem, destino)
duracao = zip(chegada, saida)
distancia = []
#df_teste['duracao'] = df_teste['chegda'] - df_teste['saida']

for o, d in caminho:
    distancia.append(geodesic(o,d))

df_teste['distancia'] = distancia

df_teste = df_teste[df_teste['distancia'] >= 1]
df_teste.reset_index(drop=True)


    #print('Endereço Origem:', geolocator.reverse(a).address)
    #print('Endereço Destino:', geolocator.reverse(b).address)
    #print(geodesic(a, b ))

,origem,destino,chegda,saida,duracao,distancia,chegada
0,"(-12.9959629, -38.4733063)","(-13.0024389, -38.4829219)",2019-01-06 18:57:24.125,2019-01-06 18:55:22.776,00:02:01.349000,1.2654845426028323 km,2019-01-06 18:57:24.125
1,"(-12.9752701, -38.4540484)","(-12.9565585, -38.4302629)",2019-01-06 18:37:54.244,2019-01-06 18:34:40.216,00:03:14.028000,3.308364509276853 km,2019-01-06 18:37:54.244
2,"(-12.9414405, -38.4136936)","(-12.9358495, -38.3952958)",2019-01-06 18:32:25.833,2019-01-06 18:30:23.340,00:02:02.493000,2.0899940590864063 km,2019-01-06 18:32:25.833
3,"(-12.9254669, -38.3778438)","(-12.9212969, -38.3639351)",2019-01-06 18:28:22.471,2019-01-06 18:26:21.342,00:02:01.129000,1.5782711165652692 km,2019-01-06 18:28:22.471
4,"(-12.9169028, -38.3452349)","(-12.9028479, -38.333298)",2019-01-06 18:24:12.099,2019-01-06 18:20:44.468,00:03:27.631000,2.0238181469700782 km,2019-01-06 18:24:12.099
5,"(-12.8776411, -38.3065261)","(-12.8913887, -38.2957841)",2019-01-05 09:52:10.885,2019-01-05 09:48:47.518,00:03:23.367000,1.9163461600695701 km,2019-01-05 09:52:10.885
6,"(-12.8854782, -38.3188271)","(-12.8936828, -38.3273954)",2019-01-03 11:16:11.057,2019-01-03 11:14:09.887,00:02:01.170000,1.299482154781203 km,2019-01-03 11:16:11.057
7,"(-12.9011716, -38.3343326)","(-12.9099348, -38.3461531)",2019-01-03 11:10:01.481,2019-01-03 11:08:01.976,00:01:59.505000,1.6079545756346247 km,2019-01-03 11:10:01.481
8,"(-12.9214238, -38.3527995)","(-12.9238852, -38.3699598)",2019-01-03 11:05:59.099,2019-01-03 11:03:57.756,00:02:01.343000,1.882009549166321 km,2019-01-03 11:05:59.099
9,"(-12.9345726, -38.3944393)","(-12.9393874, -38.4114788)",2019-01-03 11:01:55.083,2019-01-03 10:59:53.876,00:02:01.207000,1.9241872771028667 km,2019-01-03 11:01:55.083
10,"(-12.9757195, -38.4590935)","(-12.971872, -38.4387125)",2019-01-03 10:57:52.483,2019-01-03 10:55:51.560,00:02:00.923000,2.251854053477755 km,2019-01-03 10:57:52.483
11,"(-12.9789183, -38.4605886)","(-12.9768519, -38.4718617)",2019-01-03 10:53:48.011,2019-01-03 10:51:46.924,00:02:01.087000,1.2442489693545555 km,2019-01-03 10:53:48.011
12,"(-12.9776959, -38.463683)","(-12.9797103, -38.4525823)",2019-01-02 17:48:12.088,2019-01-02 17:46:08.154,00:02:03.934000,1.2248041339459976 km,2019-01-02 17:48:12.088
13,"(-12.9876981, -38.4675112)","(-12.9755783, -38.4607741)",2019-01-01 14:44:13.390,2019-01-01 14:42:11.990,00:02:01.400000,1.5271034074229406 km,2019-01-01 14:44:13.390
14,"(-12.9792464, -38.451665)","(-12.9940883, -38.4503235)",2019-01-01 13:45:14.703,2019-01-01 13:43:09.351,00:02:05.352000,1.6484024817355 km,2019-01-01 13:45:14.703
15,"(-12.9864853, -38.4582575)","(-12.9988509, -38.4548705)",2019-01-01 12:49:43.876,2019-01-01 12:46:35.776,00:03:08.100000,1.4165006748753803 km,2019-01-01 12:49:43.876
16,"(-12.9990077, -38.4630557)","(-12.9409503, -38.3585427)",2019-01-01 11:14:15.602,2019-01-01 02:12:54.000,09:01:21.602000,13.03212630421621 km,2019-01-01 11:14:15.602
17,"(-12.9121083, -38.3064123)","(-12.8933933, -38.3058899)",2018-12-31 20:24:55.058,2018-12-31 20:17:37.424,00:07:17.634000,2.0712102093261797 km,2018-12-31 20:24:55.058
18,"(-12.8761973, -38.3085454)","(-12.8681944, -38.2979402)",2018-12-31 20:05:32.001,2018-12-31 20:03:31.012,00:02:00.989000,1.4521913976886778 km,2018-12-31 20:05:32.001
19,"(-12.8578114, -38.285365)","(-12.8446629, -38.2782013)",2018-12-31 20:01:29.842,2018-12-31 19:59:20.330,00:02:09.512000,1.649414091307743 km,2018-12-31 20:01:29.842
20,"(-12.8533364, -38.2835478)","(-12.8659456, -38.2945434)",2018-12-31 19:38:30.225,2018-12-31 19:36:29.225,00:02:01,1.8358570769049098 km,2018-12-31 19:38:30.225
21,"(-12.8761694, -38.307821)","(-12.8825602, -38.3146125)",2018-12-31 19:34:28.616,2018-12-31 19:32:22.000,00:02:06.616000,1.021382694392926 km,2018-12-31 19:34:28.616
22,"(-12.8830881, -38.3156136)","(-12.8915014, -38.324791)",2018-12-31 19:27:24.741,2018-12-31 19:25:22.602,00:02:02.139000,1.3632459023145347 km,2018-12-31 19:27:24.741
23,"(-12.8977133, -38.3292712)","(-12.9033846, -38.3402213)",2018-12-31 19:23:21.595,2018-12-31 19:21:18.726,00:02:02.869000,1.343844988199858 km,2018-12-31 19:23:21.595
24,"(-12.9349231, -38.3945675)","(-12.9408186, -38.4135867)",2018-12-31 19:12:50.405,2018-12-31 19:10:37.522,00:02:12.883000,2.16441259538263 km,2018-12-31 19:12:50.405
25,"(-12.9673741, -38.4382153)","(-12.9768409, -38.4588988)",2018-12-31 19:06:34.935,2018-12-31 19:04:13.080,00:02:21.855000,2.4764548961421333 km,2018-12-31 19:06:34.935
26,"(-12.9973679, -38.4506773)","(-12.9815845, -38.4554132)",2018-12-31 11:22:35.172,2018-12-31 11:20:22.672,00:02:12.500000,1.8201464825422526 km,2018-12-31 11:22:35.172
27,"(-12.9869214, -38.4502094)","(-13.0039355, -38.4533278)",2018-12-31 09:51:36.053,2018-12-31 09:49:35.066,00:02:00.987000,1.9124379380795802 km,2018-12-31 09:51:36.053
28,"(-12.984053, -38.4836301)","(-12.9798852, -38.5032594)",2018-12-28 19:13:09.958,2018-12-28 19:10:58.968,00:02:10.990000,2.1789763834924663 km,2018-12-28 19:13:09.958
29,"(-12.9956908, -38.506729)","(-12.9925422, -38.5158018)",2018-12-28 19:04:40.845,2018-12-28 18:58:38.473,00:06:02.372000,1.0441019249245134 km,2018-12-28 19:04:40.845
...,...,...,...,...,...,...,...
46,"(-12.9967079, -38.4506522)","(-12.9865419, -38.4512439)",2018-12-24 17:49:17.844,2018-12-24 17:47:11.917,00:02:05.927000,1.1264992644342773 km,2018-12-24 17:49:17.844
47,"(-12.9724747, -38.4769458)","(-12.9835014, -38.4875942)",2018-12-24 11:32:04.007,2018-12-24 11:30:04.166,00:01:59.841000,1.6801254140997066 km,2018-12-24 11:32:04.007
48,"(-12.9779414, -38.4997901)","(-12.9873646, -38.5081635)",2018-12-24 11:11:22.223,2018-12-24 11:08:09.405,00:03:12.818000,1.3827759420543522 km,2018-12-24 11:11:22.223
49,"(-12.9781471, -38.5009239)","(-12.9873646, -38.5081635)",2018-12-24 11:06:08.364,2018-12-24 11:04:09.173,00:01:59.191000,1.287158285163894 km,2018-12-24 11:06:08.364
50,"(-12.9927378, -38.4992124)","(-12.9996915, -38.4919431)",2018-12-24 11:02:07.834,2018-12-24 10:59:45.828,00:02:22.006000,1.1016943409435946 km,2018-12-24 11:02:07.834
51,"(-13.0055164, -38.4837855)","(-12.9951172, -38.4764968)",2018-12-24 10:53:30.373,2018-12-24 10:49:06.157,00:04:24.216000,1.3959954009231634 km,2018-12-24 10:53:30.373
52,"(-12.9959064, -38.4723427)","(-13.0022992, -38.4825378)",2018-12-23 20:42:32.017,2018-12-23 20:40:31.702,00:02:00.315000,1.3128060508543538 km,2018-12-23 20:42:32.017
53,"(-12.9876518, -38.4682837)","(-12.9617919, -38.4335275)",2018-12-23 17:52:30.527,2018-12-23 17:47:54.371,00:04:36.156000,4.733324264864545 km,2018-12-23 17:52:30.527
54,"(-12.9566265, -38.4300876)","(-12.9410984, -38.4152974)",2018-12-23 17:45:47.373,2018-12-23 17:43:35.036,00:02:12.337000,2.350872477896364 km,2018-12-23 17:45:47.373
55,"(-12.9368227, -38.4046177)","(-12.9276244, -38.3865469)",2018-12-23 17:42:12.967,2018-12-23 17:40:11.724,00:02:01.243000,2.209252797591222 km,2018-12-23 17:42:12.967
56,"(-12.9451936, -38.4211251)","(-12.9671673, -38.4383695)",2018-12-23 16:06:17.375,2018-12-23 16:04:02.655,00:02:14.720000,3.0676506835805224 km,2018-12-23 16:06:17.375
57,"(-12.9759225, -38.4587)","(-12.9850035, -38.4674635)",2018-12-23 16:02:01.147,2018-12-23 15:59:58.115,00:02:03.032000,1.3832110636056187 km,2018-12-23 16:02:01.147
58,"(-13.00586, -38.4870133)","(-12.9968293, -38.4782844)",2018-12-22 09:43:36.152,2018-12-22 09:41:31.824,00:02:04.328000,1.3765362594217787 km,2018-12-22 09:43:36.152
59,"(-12.9981021, -38.4632249)","(-12.9975104, -38.4786707)",2018-12-22 01:30:24.794,2018-12-22 01:28:23.158,00:02:01.636000,1.676926686384208 km,2018-12-22 01:30:24.794
60,"(-13.0070486, -38.4924743)","(-12.999879, -38.505758)",2018-12-22 01:26:10.977,2018-12-22 01:24:02.885,00:02:08.092000,1.6449255196569785 km,2018-12-22 01:26:10.977
61,"(-12.9943234, -38.5170486)","(-12.9868641, -38.5225663)",2018-12-22 01:22:01.904,2018-12-22 01:20:00.680,00:02:01.224000,1.0194751218521438 km,2018-12-22 01:22:01.904
62,"(-12.9729174, -38.514304)","(-12.9558707, -38.5025661)",2018-12-22 01:17:59.651,2018-12-22 01:15:52.755,00:02:06.896000,2.2756335868471855 km,2018-12-22 01:17:59.651
63,"(-12.9443093, -38.501566)","(-12.9322014, -38.5045692)",2018-12-22 01:13:52.376,2018-12-22 01:11:46.161,00:02:06.215000,1.3785680460473497 km,2018-12-22 01:13:52.376
64,"(-12.9247675, -38.502807)","(-12.9357296, -38.5054819)",2018-12-21 23:50:25.509,2018-12-21 23:48:24.840,00:02:00.669000,1.2469896880167348 km,2018-12-21 23:50:25.509
65,"(-12.945619, -38.498053)","(-12.9666769, -38.4900508)",2018-12-21 23:46:21.589,2018-12-21 23:43:05.067,00:03:16.522000,2.4861825081717197 km,2018-12-21 23:46:21.589
66,"(-12.9819065, -38.4638169)","(-12.9700132, -38.4745392)",2018-12-21 21:25:50.642,2018-12-21 21:20:32.067,00:05:18.575000,1.7562832219579438 km,2018-12-21 21:25:50.642
67,"(-12.9720505, -38.4743388)","(-12.9804643, -38.477951)",2018-12-21 19:44:13.354,2018-12-21 19:41:58.937,00:02:14.417000,1.0099594512503691 km,2018-12-21 19:44:13.354
68,"(-12.9956339, -38.4733512)","(-13.0023135, -38.4823484)",2018-12-21 17:34:00.190,2018-12-21 17:31:49.779,00:02:10.411000,1.2242433637198664 km,2018-12-21 17:34:00.190
69,"(-12.9757369, -38.4571294)","(-12.9709242, -38.4389609)",2018-12-21 13:22:28.317,2018-12-21 13:20:27.223,00:02:01.094000,2.0418552009896804 km,2018-12-21 13:22:28.317
70,"(-12.9927651, -38.4409133)","(-12.9835083, -38.4395171)",2018-12-21 12:14:41.183,2018-12-21 12:11:09.254,00:03:31.929000,1.0352250780831684 km,2018-12-21 12:14:41.183
71,"(-12.9640763, -38.4346755)","(-12.9735558, -38.4528125)",2018-12-21 07:28:40.910,2018-12-21 07:26:28.363,00:02:12.547000,2.229838595242725 km,2018-12-21 07:28:40.910
72,"(-12.9751447, -38.4623196)","(-12.9849872, -38.4664667)",2018-12-21 07:24:27.491,2018-12-21 07:22:21.301,00:02:06.190000,1.1781752656113784 km,2018-12-21 07:24:27.491
73,"(-12.9765968, -38.4568256)","(-12.974896, -38.4391492)",2018-12-20 13:01:49.049,2018-12-20 12:59:43.750,00:02:05.299000,1.927014260469705 km,2018-12-20 13:01:49.049
74,"(-12.9651108, -38.437725)","(-12.9714491, -38.4460874)",2018-12-20 07:39:58.797,2018-12-20 07:38:20.868,00:01:37.929000,1.1466907886812867 km,2018-12-20 07:39:58.797
75,"(-13.0035952, -38.4530365)","(-12.9965922, -38.4435608)",2018-12-19 17:57:41.730,2018-12-19 17:55:38.407,00:02:03.323000,1.2872256031221152 km,2018-12-19 17:57:41.730

In [860]:
geolocator = Nominatim(user_agent="geoprocess", timeout=10)

df_teste2[df_teste2['distancia'] == max(df_teste2['distancia'])]
#print('Origem:', geolocator.reverse(d['origem']).address)
#print('Destino:', geolocator.reverse(d['destino']).address)
#print('Distancia:', d['distancia'].values[0])
#print('Duração: ', d['duracao'])
#print('chegada: ' , d['chegda'].values[0]).strftime('%m/%d/%Y')

,origem,destino,chegda,saida,duracao,distancia,chegada
1555,"(-12.9990077, -38.4630557)","(-12.9409503, -38.3585427)",2019-01-01 11:14:15.602,2019-01-01 02:12:54,09:01:21.602000,13.03212630421621 km,2019-01-01 11:14:15.602

In [ ]:
# Criar um df com distancia e data (yyy-mm-dd) para permitir analise por dia, mes e ano
# http://kivanpolimis.com/location-data-exploration-1.html